version: '3'

services:
  whoami1:
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami1.rule=Host(`whoami1.localhost`)"
    networks:
        traefik:
            ipv4_address: 172.16.1.3

networks:
    traefik:
        external:
            name: traefik